type Level = 'beginner' | 'intermediate' | 'advanced'

type Player = {
    level: Level
    name: string
    inGame?: boolean
    idleTooLong?: boolean
    gamesPlayed: number
    gamesWon: number
    attendance: number
    queuePosition: number
}

export const players: Player[] = [
    {
        level: 'beginner',
        name: 'Alex Rivera',
        inGame: true,
        gamesPlayed: 4,
        gamesWon: 1,
        attendance: 88,
        queuePosition: 0,
    },
    {
        level: 'intermediate',
        name: 'Sarah Chen',
        inGame: true,
        gamesPlayed: 16,
        gamesWon: 9,
        attendance: 95,
        queuePosition: 0,
    },
    {
        level: 'advanced',
        name: 'Marcus Vance',
        inGame: true,
        gamesPlayed: 32,
        gamesWon: 24,
        attendance: 99,
        queuePosition: 0,
    },
    {
        level: 'beginner',
        name: 'Emily Watson',
        inGame: true,
        gamesPlayed: 6,
        gamesWon: 2,
        attendance: 82,
        queuePosition: 0,
    },
    {
        level: 'intermediate',
        name: 'David Kim',
        gamesPlayed: 14,
        gamesWon: 7,
        attendance: 91,
        queuePosition: 1,
    },
    {
        level: 'advanced',
        name: 'Elena Rostova',
        gamesPlayed: 28,
        gamesWon: 21,
        attendance: 97,
        queuePosition: 2,
    },
    {
        level: 'beginner',
        name: 'Liam O\'Connor',
        gamesPlayed: 3,
        gamesWon: 0,
        attendance: 75,
        queuePosition: 3,
    },
    {
        level: 'intermediate',
        name: 'Sophia Patel',
        idleTooLong: true,
        gamesPlayed: 19,
        gamesWon: 11,
        attendance: 89,
        queuePosition: 4,
    },
    {
        level: 'advanced',
        name: 'Lucas Silva',
        gamesPlayed: 45,
        gamesWon: 33,
        attendance: 96,
        queuePosition: 5,
    },
    {
        level: 'beginner',
        name: 'Noah Tanaka',
        gamesPlayed: 9,
        gamesWon: 4,
        attendance: 84,
        queuePosition: 6,
    },
    {
        level: 'intermediate',
        name: 'Olivia Martinez',
        gamesPlayed: 22,
        gamesWon: 13,
        attendance: 93,
        queuePosition: 7,
    },
    {
        level: 'advanced',
        name: 'Ethan Hunt',
        gamesPlayed: 38,
        gamesWon: 29,
        attendance: 100,
        queuePosition: 8,
    },
    {
        level: 'beginner',
        name: 'Ava Jackson',
        idleTooLong: true,
        gamesPlayed: 2,
        gamesWon: 1,
        attendance: 70,
        queuePosition: 9,
    },
    {
        level: 'intermediate',
        name: 'Mason Thorne',
        gamesPlayed: 11,
        gamesWon: 5,
        attendance: 86,
        queuePosition: 10,
    },
    {
        level: 'advanced',
        name: 'Isabella Cruz',
        gamesPlayed: 50,
        gamesWon: 41,
        attendance: 98,
        queuePosition: 11,
    },
    {
        level: 'beginner',
        name: 'Logan Brooks',
        gamesPlayed: 7,
        gamesWon: 3,
        attendance: 90,
        queuePosition: 12,
    },
    {
        level: 'intermediate',
        name: 'Mia Wallace',
        gamesPlayed: 25,
        gamesWon: 14,
        attendance: 94,
        queuePosition: 13,
    },
    {
        level: 'advanced',
        name: 'James Mercer',
        idleTooLong: true,
        gamesPlayed: 29,
        gamesWon: 20,
        attendance: 91,
        queuePosition: 14,
    },
    {
        level: 'beginner',
        name: 'Charlotte Dubois',
        gamesPlayed: 5,
        gamesWon: 2,
        attendance: 78,
        queuePosition: 15,
    },
    {
        level: 'intermediate',
        name: 'Benjamin Hayes',
        gamesPlayed: 17,
        gamesWon: 10,
        attendance: 88,
        queuePosition: 16,
    },
    {
        level: 'advanced',
        name: 'Amelia Zhang',
        gamesPlayed: 36,
        gamesWon: 27,
        attendance: 95,
        queuePosition: 17,
    },
    {
        level: 'beginner',
        name: 'Henry Sterling',
        gamesPlayed: 1,
        gamesWon: 0,
        attendance: 65,
        queuePosition: 18,
    },
    {
        level: 'intermediate',
        name: 'Harper Vance',
        gamesPlayed: 21,
        gamesWon: 12,
        attendance: 92,
        queuePosition: 19,
    },
    {
        level: 'advanced',
        name: 'Alexander Wright',
        gamesPlayed: 41,
        gamesWon: 30,
        attendance: 99,
        queuePosition: 20,
    },
    {
        level: 'beginner',
        name: 'Evelyn Foster',
        idleTooLong: true,
        gamesPlayed: 8,
        gamesWon: 3,
        attendance: 83,
        queuePosition: 21,
    },
    {
        level: 'intermediate',
        name: 'Sebastian Shaw',
        gamesPlayed: 13,
        gamesWon: 6,
        attendance: 87,
        queuePosition: 22,
    },
    {
        level: 'advanced',
        name: 'Abigail Rossi',
        gamesPlayed: 30,
        gamesWon: 22,
        attendance: 96,
        queuePosition: 23,
    },
    {
        level: 'beginner',
        name: 'Daniel Park',
        gamesPlayed: 10,
        gamesWon: 4,
        attendance: 89,
        queuePosition: 24,
    },
    {
        level: 'intermediate',
        name: 'Emily Rhodes',
        gamesPlayed: 18,
        gamesWon: 9,
        attendance: 90,
        queuePosition: 25,
    },
    {
        level: 'advanced',
        name: 'Matthew Drake',
        gamesPlayed: 33,
        gamesWon: 25,
        attendance: 97,
        queuePosition: 26,
    },
    {
        level: 'beginner',
        name: 'Scarlett Johansson',
        gamesPlayed: 4,
        gamesWon: 1,
        attendance: 81,
        queuePosition: 27,
    },
    {
        level: 'intermediate',
        name: 'Jackson Miller',
        idleTooLong: true,
        gamesPlayed: 23,
        gamesWon: 11,
        attendance: 85,
        queuePosition: 28,
    },
    {
        level: 'advanced',
        name: 'Victoria Song',
        gamesPlayed: 47,
        gamesWon: 38,
        attendance: 98,
        queuePosition: 29,
    },
    {
        level: 'beginner',
        name: 'Mateo Gomez',
        gamesPlayed: 6,
        gamesWon: 2,
        attendance: 79,
        queuePosition: 30,
    },
    {
        level: 'intermediate',
        name: 'Chloe Bennett',
        gamesPlayed: 15,
        gamesWon: 8,
        attendance: 91,
        queuePosition: 31,
    },
    {
        level: 'advanced',
        name: 'David Hassel',
        gamesPlayed: 26,
        gamesWon: 19,
        attendance: 94,
        queuePosition: 32,
    },
    {
        level: 'beginner',
        name: 'Grace Hopper',
        gamesPlayed: 3,
        gamesWon: 1,
        attendance: 87,
        queuePosition: 33,
    },
    {
        level: 'intermediate',
        name: 'Samuel Lee',
        gamesPlayed: 20,
        gamesWon: 11,
        attendance: 93,
        queuePosition: 34,
    },
    {
        level: 'advanced',
        name: 'Hannah Abbott',
        gamesPlayed: 35,
        gamesWon: 26,
        attendance: 96,
        queuePosition: 35,
    },
    {
        level: 'beginner',
        name: 'Oliver Queen',
        idleTooLong: true,
        gamesPlayed: 7,
        gamesWon: 2,
        attendance: 76,
        queuePosition: 36,
    },
    {
        level: 'intermediate',
        name: 'Zoe Kravitz',
        gamesPlayed: 16,
        gamesWon: 10,
        attendance: 89,
        queuePosition: 37,
    },
    {
        level: 'advanced',
        name: 'Gabriel Macht',
        gamesPlayed: 42,
        gamesWon: 31,
        attendance: 99,
        queuePosition: 38,
    },
    {
        level: 'beginner',
        name: 'Lily Aldrin',
        gamesPlayed: 5,
        gamesWon: 2,
        attendance: 85,
        queuePosition: 39,
    },
    {
        level: 'intermediate',
        name: 'Anthony Edwards',
        gamesPlayed: 24,
        gamesWon: 13,
        attendance: 92,
        queuePosition: 40,
    },
    {
        level: 'advanced',
        name: 'Natalie Portman',
        gamesPlayed: 31,
        gamesWon: 23,
        attendance: 95,
        queuePosition: 41,
    },
    {
        level: 'beginner',
        name: 'Dylan O\'Brien',
        gamesPlayed: 2,
        gamesWon: 0,
        attendance: 72,
        queuePosition: 42,
    },
    {
        level: 'intermediate',
        name: 'Samantha Carter',
        gamesPlayed: 12,
        gamesWon: 7,
        attendance: 88,
        queuePosition: 43,
    },
    {
        level: 'advanced',
        name: 'Christopher Nolan',
        idleTooLong: true,
        gamesPlayed: 39,
        gamesWon: 30,
        attendance: 93,
        queuePosition: 44,
    },
    {
        level: 'beginner',
        name: 'Maya Lin',
        gamesPlayed: 9,
        gamesWon: 3,
        attendance: 86,
        queuePosition: 45,
    },
    {
        level: 'intermediate',
        name: 'Isaac Newton',
        gamesPlayed: 27,
        gamesWon: 15,
        attendance: 94,
        queuePosition: 46,
    },
]